title: "Eric Xu"
author: "Eric Xu"
description: "Hello!"

# Social links (remove any you don't want)
github_username: "EricYXu"
linkedin_username: "Eric-Yang-Xu"
# email: "your@email.com"
# twitter_username: yourhandle

theme: "minima"

plugins:
  - jekyll-feed
  - jekyll-sitemap
